# Extend from the base vllm image
FROM vllm/vllm-openai:latest

# Override the base image's entrypoint with a shell
ENTRYPOINT ["/bin/bash"]

# Install development tools and utilities
RUN apt-get update && apt-get install -y \
    gdb \
    ninja-build \
    vim \
    tmux \
    htop \
    wget \
    curl \
    locales \
    lsof \
    git \
    git-lfs \
    zsh \
    tree \
    silversearcher-ag \
    cloc \
    unzip \
    pkg-config \
    libssl-dev \
    bear \
    ccache \
    && apt install -y rdma-core infiniband-diags openssh-server perftest ibverbs-providers libibumad3 libibverbs1 libnl-3-200 libnl-route-3-200 librdmacm1 \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN apt update -y \
    && apt install -y --no-install-recommends gnupg \
    && echo "deb http://developer.download.nvidia.com/devtools/repos/ubuntu2004/amd64 /" | tee /etc/apt/sources.list.d/nvidia-devtools.list \
    && apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub \
    && apt update -y \
    && apt install nsight-systems-cli -y

# Set up locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Install minimal Python packages
RUN python3 -m pip install --no-cache-dir \
    pytest \
    black \
    isort \
    icdiff \
    scikit_build_core \
    uv \
    pre-commit

# Install diff-so-fancy
RUN curl -LSso /usr/local/bin/diff-so-fancy https://github.com/so-fancy/diff-so-fancy/releases/download/v1.4.4/diff-so-fancy \
    && chmod +x /usr/local/bin/diff-so-fancy

# Install clang-format
RUN curl -LSso /usr/local/bin/clang-format https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-32d3ac78/clang-format-16_linux-amd64 \
    && chmod +x /usr/local/bin/clang-format

# Install clangd
RUN curl -L https://github.com/clangd/clangd/releases/download/18.1.3/clangd-linux-18.1.3.zip -o clangd.zip \
    && unzip clangd.zip \
    && cp -r clangd_18.1.3/bin/* /usr/local/bin/ \
    && cp -r clangd_18.1.3/lib/* /usr/local/lib/ \
    && rm -rf clangd_18.1.3 clangd.zip

# Install CMake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.31.1/cmake-3.31.1-linux-x86_64.tar.gz \
    && tar -xzf cmake-3.31.1-linux-x86_64.tar.gz \
    && cp -r cmake-3.31.1-linux-x86_64/bin/* /usr/local/bin/ \
    && cp -r cmake-3.31.1-linux-x86_64/share/* /usr/local/share/ \
    && rm -rf cmake-3.31.1-linux-x86_64 cmake-3.31.1-linux-x86_64.tar.gz

# Add yank script
RUN echo '#!/bin/bash' > /usr/local/bin/yank && \
    echo 'put() {' >> /usr/local/bin/yank && \
    echo '  esc=$1' >> /usr/local/bin/yank && \
    echo '  test -n "$TMUX" -o -z "${TERM##screen*}" && esc="\033Ptmux;\033$esc\033\\"' >> /usr/local/bin/yank && \
    echo '  printf "$esc"' >> /usr/local/bin/yank && \
    echo '}' >> /usr/local/bin/yank && \
    echo 'put "\033]52;c;!\a"' >> /usr/local/bin/yank && \
    echo 'buf=$( cat "$@" )' >> /usr/local/bin/yank && \
    echo 'len=$( printf %s "$buf" | wc -c ) max=74994' >> /usr/local/bin/yank && \
    echo 'test $len -gt $max && echo "$0: input is $(( len - max )) bytes too long" >&2' >> /usr/local/bin/yank && \
    echo 'put "\033]52;c;$( printf %s "$buf" | head -c $max | base64 | tr -d '\''\r\n'\'' )\a"' >> /usr/local/bin/yank && \
    echo 'test -n "$TMUX" && tmux set-buffer "$buf" ||:' >> /usr/local/bin/yank && \
    chmod +x /usr/local/bin/yank

# Install oh-my-zsh and plugins
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended \
    && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions \
    && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Configure Vim
RUN echo 'function! Yank(text) abort' > /root/.vimrc && \
    echo '  let escape = system("yank", a:text)' >> /root/.vimrc && \
    echo '  if v:shell_error' >> /root/.vimrc && \
    echo '    echoerr escape' >> /root/.vimrc && \
    echo '  else' >> /root/.vimrc && \
    echo '    call writefile([escape], "/dev/tty", "b")' >> /root/.vimrc && \
    echo '  endif' >> /root/.vimrc && \
    echo 'endfunction' >> /root/.vimrc && \
    echo '' >> /root/.vimrc && \
    echo 'noremap <silent> <Leader>y y:<C-U>call Yank(@0)<CR>' >> /root/.vimrc && \
    echo '' >> /root/.vimrc && \
    echo '" automatically run yank(1) whenever yanking in Vim' >> /root/.vimrc && \
    echo 'function! CopyYank() abort' >> /root/.vimrc && \
    echo '  call Yank(join(v:event.regcontents, "\n"))' >> /root/.vimrc && \
    echo 'endfunction' >> /root/.vimrc && \
    echo '' >> /root/.vimrc && \
    echo 'autocmd TextYankPost * call CopyYank()' >> /root/.vimrc && \
    echo '' >> /root/.vimrc && \
    echo '" Basic settings' >> /root/.vimrc && \
    echo 'set number' >> /root/.vimrc && \
    echo 'syntax on' >> /root/.vimrc && \
    echo 'set mouse=a' >> /root/.vimrc && \
    echo 'filetype indent on' >> /root/.vimrc && \
    echo '' >> /root/.vimrc && \
    echo '" Indentation' >> /root/.vimrc && \
    echo 'set autoindent nosmartindent' >> /root/.vimrc && \
    echo 'set smarttab' >> /root/.vimrc && \
    echo 'set expandtab' >> /root/.vimrc && \
    echo 'set shiftwidth=4' >> /root/.vimrc && \
    echo 'set softtabstop=4' >> /root/.vimrc && \
    echo '' >> /root/.vimrc && \
    echo '" Visual guides' >> /root/.vimrc && \
    echo 'set colorcolumn=120' >> /root/.vimrc && \
    echo 'highlight ColorColumn ctermbg=5' >> /root/.vimrc && \
    echo '' >> /root/.vimrc && \
    echo '" Status line' >> /root/.vimrc && \
    echo 'set laststatus=2' >> /root/.vimrc && \
    echo 'set statusline=%<%f\ %h%m%r%=%{\"[\".(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\").\"]\ \"}%k\ %-14.(%l,%c%V%)\ %P' >> /root/.vimrc && \
    echo '' >> /root/.vimrc && \
    echo '" Backspace behavior' >> /root/.vimrc && \
    echo 'set backspace=2' >> /root/.vimrc && \
    echo '' >> /root/.vimrc && \
    echo '" Encoding' >> /root/.vimrc && \
    echo 'set encoding=utf-8' >> /root/.vimrc && \
    echo 'set fileencoding=utf-8' >> /root/.vimrc

# Configure tmux
RUN echo '# Pane border styling' > /root/.tmux.conf && \
    echo 'set -g pane-border-style fg=#742727,bg=black' >> /root/.tmux.conf && \
    echo 'set -g pane-active-border-style fg=red,bg=black' >> /root/.tmux.conf && \
    echo '' >> /root/.tmux.conf && \
    echo '# Status bar styling' >> /root/.tmux.conf && \
    echo 'set -g status-style bg=#0C8A92,fg=black' >> /root/.tmux.conf && \
    echo '' >> /root/.tmux.conf && \
    echo '# Change prefix key to backtick' >> /root/.tmux.conf && \
    echo 'set-option -g prefix `' >> /root/.tmux.conf && \
    echo 'unbind C-b' >> /root/.tmux.conf && \
    echo 'bind-key ` send-prefix' >> /root/.tmux.conf && \
    echo '' >> /root/.tmux.conf && \
    echo '# Split panes using - and = with current path' >> /root/.tmux.conf && \
    echo 'unbind \"' >> /root/.tmux.conf && \
    echo 'bind - splitw -v -c \"#{pane_current_path}\"' >> /root/.tmux.conf && \
    echo 'unbind %' >> /root/.tmux.conf && \
    echo 'bind = splitw -h -c \"#{pane_current_path}\"' >> /root/.tmux.conf && \
    echo '' >> /root/.tmux.conf && \
    echo '# Vi mode settings' >> /root/.tmux.conf && \
    echo 'bind-key -T copy-mode-vi Y send-keys -X copy-pipe \"yank > #{pane_tty}\"' >> /root/.tmux.conf && \
    echo 'set-window-option -g mode-keys vi' >> /root/.tmux.conf && \
    echo '' >> /root/.tmux.conf && \
    echo '# Other settings' >> /root/.tmux.conf && \
    echo 'set-option -g escape-time 0' >> /root/.tmux.conf && \
    echo 'set-option -g base-index 1' >> /root/.tmux.conf && \
    echo 'set-window-option -g mouse on' >> /root/.tmux.conf

# Configure Git
RUN git config --global core.editor "vim" \
    && git config --global core.whitespace "fix,-indent-with-non-tab,trailing-space,cr-at-eol" \
    && git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX" \
    && git config --global color.ui true \
    && git config --global color."diff-highlight".oldNormal "red bold" \
    && git config --global color."diff-highlight".oldHighlight "red bold 52" \
    && git config --global color."diff-highlight".newNormal "green bold" \
    && git config --global color."diff-highlight".newHighlight "green bold 22" \
    && git config --global color.diff.meta "11" \
    && git config --global color.diff.frag "magenta bold" \
    && git config --global color.diff.commit "yellow bold" \
    && git config --global color.diff.old "red bold" \
    && git config --global color.diff.new "green bold" \
    && git config --global color.diff.whitespace "red reverse" \
    && git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%Creset%C(auto)%d%Creset' --abbrev-commit --" \
    && git config --global http.sslVerify false \
    && git config --global pull.rebase true

# Configure zsh
COPY --chown=root:root <<-"EOF" /root/.zshrc
export ZSH="/root/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(
    git
    z
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias vi='vim'

# Enhanced history
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt INC_APPEND_HISTORY
EOF

# Set workspace directory
WORKDIR /vllm-workspace

RUN git clone --depth=1 https://github.com/vllm-project/vllm.git

# Create .devcontainer and .vscode directories
RUN mkdir -p /vllm-workspace/vllm/.devcontainer /vllm-workspace/vllm/.vscode

# Copy .devcontainer and .vscode from host to container
COPY .devcontainer /vllm-workspace/vllm/.devcontainer/

ENV PYTHONPATH=/vllm-workspace/vllm
